apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendstore-app-deployment
  labels:
    app: trendstore-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trendstore-app
  template:
    metadata:
      labels:
        app: trendstore-app
    spec:
      containers:
        - name: trendstore-app
          image: wikkics/trendstore-app:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
